# Generated by Django 2.2 on 2020-03-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthuser',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='标题'),
        ),
    ]
