# Generated by Django 2.2 on 2020-03-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='用户昵称'),
        ),
    ]
