# Generated by Django 2.2 on 2020-03-19 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='标题')),
                ('orders', models.IntegerField(verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='结束时间')),
                ('money', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='打赏金额')),
                ('status', models.SmallIntegerField(choices=[(0, '未付款'), (1, '已付款'), (2, '已取消'), (3, '超时取消')], default=0, verbose_name='打赏状态')),
                ('reward_type', models.SmallIntegerField(choices=[(0, '支付宝'), (1, '余额')], default=0, verbose_name='打赏类型')),
                ('trade_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='流水号')),
                ('out_trade_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='支付平台返回的流水号')),
                ('message', models.TextField(blank=True, null=True, verbose_name='打赏留言')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='article.ArticleModel', verbose_name='文章')),
            ],
            options={
                'verbose_name': '打赏记录',
                'verbose_name_plural': '打赏记录',
                'db_table': 'rr_user_reward',
            },
        ),
    ]
