# Generated by Django 2.2 on 2020-03-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCollectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='标题')),
                ('orders', models.IntegerField(verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '文集',
                'verbose_name_plural': '文集',
                'db_table': 'rr_article_collection',
            },
        ),
        migrations.CreateModel(
            name='ArticleImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='标题')),
                ('orders', models.IntegerField(verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='结束时间')),
                ('group', models.CharField(blank=True, max_length=15, null=True, verbose_name='组名')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片地址')),
                ('user', models.IntegerField(blank=True, null=True, verbose_name='上传图片的用户')),
            ],
            options={
                'verbose_name': '文章图片',
                'verbose_name_plural': '文章图片',
                'db_table': 'rr_article_image',
            },
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='标题')),
                ('orders', models.IntegerField(verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='结束时间')),
                ('content', models.TextField(blank=True, null=True, verbose_name='文章内容')),
                ('render', models.TextField(blank=True, null=True, verbose_name='文章内容[解析后]')),
                ('pub_date', models.DateTimeField(default=None, null=True, verbose_name='发布时间')),
                ('access_pwd', models.CharField(blank=True, max_length=15, null=True, verbose_name='访问密码')),
                ('read_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='阅读量')),
                ('link_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞量')),
                ('collect_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏量')),
                ('comment_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='评论量')),
                ('reward_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='赞赏量')),
                ('is_publish', models.BooleanField(default=False, verbose_name='是否公开')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'rr_article',
            },
        ),
        migrations.CreateModel(
            name='ArticlePostLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='标题')),
                ('orders', models.IntegerField(verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='结束时间')),
                ('status', models.IntegerField(choices=[(0, '未审核'), (1, '审核通过'), (2, '审核未通过')], default=0, verbose_name='审核状态')),
                ('manager', models.IntegerField(blank=True, default=None, null=True, verbose_name='审核人')),
                ('post_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='审核时间')),
            ],
            options={
                'verbose_name': '文章的投稿记录',
                'verbose_name_plural': '文章的投稿记录',
                'db_table': 'rr_article_post_log',
            },
        ),
        migrations.CreateModel(
            name='SpecialArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='标题')),
                ('orders', models.IntegerField(verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '专题的文章',
                'verbose_name_plural': '专题的文章',
                'db_table': 'rr_special_article',
            },
        ),
        migrations.CreateModel(
            name='SpecialCollectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='标题')),
                ('orders', models.IntegerField(verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '专题收藏',
                'verbose_name_plural': '专题收藏',
                'db_table': 'rr_special_collection',
            },
        ),
        migrations.CreateModel(
            name='SpecialFocusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='标题')),
                ('orders', models.IntegerField(verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '专题的关注',
                'verbose_name_plural': '专题的关注',
                'db_table': 'rr_special_focus',
            },
        ),
        migrations.CreateModel(
            name='SpecialManagerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='标题')),
                ('orders', models.IntegerField(verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '专题的管理员',
                'verbose_name_plural': '专题的管理员',
                'db_table': 'rr_special_manager',
            },
        ),
        migrations.CreateModel(
            name='SpecialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='标题')),
                ('orders', models.IntegerField(verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='结束时间')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='封面图片')),
                ('notice', models.TextField(blank=True, null=True, verbose_name='专题公告')),
                ('article_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='文章总数')),
                ('follow_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='关注量')),
                ('collect_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏量')),
            ],
            options={
                'verbose_name': '专题',
                'verbose_name_plural': '专题',
                'db_table': 'rr_special',
            },
        ),
    ]
