# Generated by Django 2.2 on 2020-03-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='title',
        ),
        migrations.AlterField(
            model_name='articlecollectionmodel',
            name='name',
            field=models.CharField(max_length=150, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='specialmodel',
            name='name',
            field=models.CharField(max_length=150, verbose_name='标题'),
        ),
    ]
