# Generated by Django 2.2 on 2020-03-19 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='specialmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='specialmanagermodel',
            name='special',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_list', to='article.SpecialModel', verbose_name='专题'),
        ),
        migrations.AddField(
            model_name='specialmanagermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='special_list', to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
        migrations.AddField(
            model_name='specialfocusmodel',
            name='special',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.SpecialModel', verbose_name='专题'),
        ),
        migrations.AddField(
            model_name='specialfocusmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
        migrations.AddField(
            model_name='specialcollectionmodel',
            name='special',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.SpecialModel', verbose_name='专题'),
        ),
        migrations.AddField(
            model_name='specialcollectionmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
        migrations.AddField(
            model_name='specialarticlemodel',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_special_list', to='article.ArticleModel', verbose_name='文章'),
        ),
        migrations.AddField(
            model_name='specialarticlemodel',
            name='special',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_article_list', to='article.SpecialModel', verbose_name='专题'),
        ),
        migrations.AddField(
            model_name='articlepostlogmodel',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleModel', verbose_name='文章'),
        ),
        migrations.AddField(
            model_name='articlepostlogmodel',
            name='special',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.SpecialModel', verbose_name='专题'),
        ),
        migrations.AddField(
            model_name='articlepostlogmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='投稿人'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleCollectionModel', verbose_name='文集'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='articlecollectionmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
