# Generated by Django 2.2 on 2020-03-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200313_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='render',
            field=models.TextField(blank=True, null=True, verbose_name='文章内容[解析后]'),
        ),
    ]
