# Generated by Django 2.2 on 2020-03-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200317_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecollectionmodel',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='articleimagemodel',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='articlepostlogmodel',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='specialarticlemodel',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='specialcollectionmodel',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='specialfocusmodel',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='specialmanagermodel',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='specialmodel',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='标题'),
        ),
    ]
