# Generated by Django 2.2 on 2020-03-17 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200317_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialarticlemodel',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_special_list', to='article.ArticleModel', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='specialarticlemodel',
            name='special',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_article_list', to='article.SpecialModel', verbose_name='专题'),
        ),
    ]
