# Generated by Django 2.2 on 2020-03-19 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='结束时间')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='轮播图')),
                ('name', models.CharField(max_length=150, verbose_name='轮播图名称')),
                ('note', models.CharField(max_length=500, verbose_name='备注信息')),
                ('is_http', models.BooleanField(default=True, help_text='如果是站内地址,则默认勾选', verbose_name='是否站内链接')),
                ('link', models.CharField(help_text='如果是站外链接,必须加上协议,格式如:http://www.renran.com', max_length=500, verbose_name='轮播图广告地址')),
                ('start_time', models.DateTimeField(verbose_name='开始展示时间')),
                ('end_time', models.DateTimeField(verbose_name='结束展示时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'rr_banner',
            },
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='标题')),
                ('orders', models.IntegerField(verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='结束时间')),
                ('is_http', models.BooleanField(default=True, help_text='如果是站内地址,则默认勾选', verbose_name='是否站内链接')),
                ('link', models.CharField(help_text='如果是站外链接,必须加上协议,格式如:http://www.renran.com', max_length=500, verbose_name='导航地址')),
                ('option', models.SmallIntegerField(choices=[(1, '头部导航'), (2, '脚部导航')], default=1, verbose_name='导航位置')),
                ('icon', models.CharField(blank=True, default='el-icon-info', max_length=100, null=True, verbose_name='icon图标')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='son', to='home.Nav', verbose_name='父亲导航')),
            ],
            options={
                'verbose_name': '导航菜单',
                'verbose_name_plural': '导航菜单',
                'db_table': 'rr_nav',
            },
        ),
    ]
