# Generated by Django 2.2 on 2020-03-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='icon',
            field=models.CharField(blank=True, default='el-icon-info', max_length=100, null=True, verbose_name='icon图标'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='icon',
            field=models.CharField(blank=True, default='el-icon-info', max_length=100, null=True, verbose_name='icon图标'),
        ),
    ]
