# Generated by Django 2.2 on 2020-03-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nav',
            name='icon',
        ),
    ]
