# Generated by Django 2.2 on 2020-03-09 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='icon',
        ),
    ]
