# Generated by Django 2.2 on 2020-03-06 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束展示时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始展示时间'),
            preserve_default=False,
        ),
    ]
