# Generated by Django 2.2 on 2020-03-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_banner_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='标题'),
        ),
    ]
